### ISSUE TITLE
Resource License Request

### ISSUE THREAD

**Issue by jtsylve** [aff4/aff4-java#1]
Could you please specify a different license for the tests (or at the very least the files in `src/test/resources`)?  I would like to use them in tests for my reader to keep the tests consistent across implementations, but LGPL isn't going to work for me, as that license doesn't make much sense with Go, which pretty much requires static linking for all the things.

**Comment by blschatz** [comment]
Licence on test source code changed to Apache, and Apache licence declared for the sample images.
