### ISSUE TITLE
invalid LOC header (bad signature)

### ISSUE THREAD

**Issue by Mrucznik** [aff4/aff4-java#3]
Hello
When I run examples (Digest, Export or Information) on aff4 images created by tool: winpmem (https://github.com/Velocidex/c-aff4/releases) i get this error:

> [ERROR] 00:04.393(Containers.java:getResourceID:136) invalid LOC header (bad signature)
> java.util.zip.ZipException: invalid LOC header (bad signature)
> 	at java.util.zip.ZipFile.read(Native Method)
> 	at java.util.zip.ZipFile.access$1400(ZipFile.java:60)
> 	at java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:734)
> 	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
> 	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
> 	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
> 	at java.io.InputStreamReader.read(InputStreamReader.java:184)
> 	at java.io.Reader.read(Reader.java:140)
> 	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2369)
> 	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2348)
> 	at org.apache.commons.io.IOUtils.copy(IOUtils.java:2325)
> 	at org.apache.commons.io.IOUtils.copy(IOUtils.java:2273)
> 	at org.apache.commons.io.IOUtils.toString(IOUtils.java:1041)
> 	at com.evimetry.aff4.Containers.getResourceID(Containers.java:132)
> 	at com.evimetry.aff4.Containers.openContainer(Containers.java:91)
> 	at com.evimetry.aff4.Containers.open(Containers.java:54)
> 	at com.evimetry.aff4.examples.Information.main(Information.java:58)
> [ERROR] 00:05.377(Information.java:main:95) org.apache.jena.atlas.RuntimeIOException: java.nio.channels.ClosedChannelException

Help!

**Comment by blschatz** [comment]
I seem to recall that winpmem's zip implementation was generating invalid Zip64 location headers. The exception you are seeing is Java's ZIP implementation saying as much.

**Comment by scudette** [comment]
I believe Java's implementation is wrong here. This should be fixed on the java side or it will be unable to read uncompressed segments in large files (>4Gb).  Since Winpmem produces those for memory images it should be supported.
